a_lims: null
n_plans: 100
horizon: 10
multistep: 1
n_samples_o: 300
n_steps_o: 50
lr_o: 0.0001
use_info_gain: false
use_observation_preference: true
use_ukf_obs_pref: false
use_pragmatic_value: true
scale_pragmatic_value: 1
select_max_pi: true
n_samples_ig_s: 3
n_samples_ig_o: 3
n_samples_obs_pref_s: 100
n_samples_obs_pref_o: 10
n_samples_a: 30
n_samples_a_noise_sys: 100
n_samples_a_combine: 200
use_complete_ukf: true
exp_normal_sys_params: false
C_index: null
sys_dependent_C: null
state_dependent_C : null
action_prior: null
use_fixed_plans: false
state_scaling: null
reaction_time: 0.0
grouped_state_updates: null
exclude_observation_indices: null
ic_minimal_open_loop_steps: 0
use_ic: false
ic_div_threshold: null
ic_efe_threshold: null
ic_efe_type: null
ic_use_remaining_nefe: false
prob_dynamics: null
ii_threshold: null